{{- if ne .Values.global.mode "quickstart" }}
{{- if and .Values.slave.persistence.enabled (not .Values.slave.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.slave.persistence.claim.name }}
spec:
  {{ toYaml .Values.slave.persistence.claim.spec | indent 2 }}
{{- end }}
{{- end }}

